### ISSUE TITLE
Error on running 

### ISSUE THREAD

**Issue by justluthra** [Proviesec/PSFuzz#3]
<img width="929" alt="Screenshot 2022-11-26 at 2 17 12 AM" src="https://user-images.githubusercontent.com/98668772/204053982-1a8915fb-be53-4a6d-a0a8-aee7da5d8e34.png">

**Comment by provie** [comment]
you need to add a backslah at the url: https://www.google.de/
But I have added a backslah check function: https://github.com/Proviesec/PSFuzz/commit/08e11dcceb6be0e289b0696f525f2e6e1cc71ee5
